### ISSUE TITLE
Image Undistortion components need update

### ISSUE THREAD

**Issue by ulricheck** [Ubitrack/component_vision#3]
Currently there is no Component for Image Undistortion available that can be used with the default camera nodes (e.g. a camera that provides CameraIntrinsics).

- ImageUndistortion requires an edge between Distorted/Undistorted ImagePlane (CameraIntrinsics)
- UndistortImage requires a 3x3 Intrinsics matrix and a Vector4 for Distortion coefficients.. but no components are available to actually split a CameraIntrinsics measurement into these measurements.

**Comment by FriederPankratz** [comment]
the new undistortion component is updated to the intrinsics format
